### ISSUE TITLE
How to find sample rate?

### ISSUE THREAD

**Issue by kj7rrv** [AI5GW/Goertzel#4]
Hello!

I am working on a DTMF decoder using this library. I am using it on a Raspberry Pi Pico right now; my final project will be on an Adafruit Feather RP2040. They have the same chip, so the difference won't matter. I'm underclocking to 18 MHz to save power.

How do I determine the sample rate for my board?

73!

**Comment by AI5GW** [comment]
The best case would of course be if you can set the sampling rate to a known frequency. If you have to determine the free running sampling rate, you could acquire a large amount of samples, let's say 1000, and measure the time from the start of the acquisition and after the 1000 samples are complete. From that you can determine how many samples you can gather per second.
