### ISSUE TITLE
Move 1.0.1 Tag to current main branch

### ISSUE THREAD

**Issue by JohnHurstIV** [AI5GW/Goertzel#5]
The 1.0.1 tag was applied to the repo before the properties.json file was updated to 1.0.1 properly. The tag needs to be moved in order for the arduino library registry to update on it's end. The update will be something along the lines of

```
git tag -d <tagname>                  # delete the old tag locally
git push origin :refs/tags/<tagname>  # delete the old tag remotely
git tag <tagname> <commitId>          # make a new tag locally
git push origin <tagname>             # push the new local tag to the remote
```

Thanks!

**Comment by AI5GW** [comment]
Hi John, I noticed this error. I'll get on it shortly when I have some more time for personal projects. Migth actually be that Tag / Version 1.0.2 needs to be applied since the library registry already overjumped the tag. I'll figure it out.

**Comment by zeroping** [comment]
Hi @AI5GW, I hit the issues in the current version in Arduino (1.0.0), and found my way here. I was hoping you could take a chance to look into this tagging so the updates are easily usable in Arduino.

Thanks!

**Comment by AI5GW** [comment]
Hi all, I deleted the 1.0.1 release, updated all Version information to 1.0.**2** and added a new release with tag 1.0.2. Let's see if this will be pushed into the library manager successfully. Thanks for the patience!

**Comment by AI5GW** [comment]
1.0.2 has been checked out successfully
